import React,{useEffect,useMemo}from'react';import{DarkTheme,DefaultTheme,NavigationContainer}from'@react-navigation/native';import{createBottomTabNavigator}from'@react-navigation/bottom-tabs';import{createNativeStackNavigator}from'@react-navigation/native-stack';import{StatusBar}from'expo-status-bar';import{Platform,Text,View}from'react-native';import{SafeAreaProvider,useSafeAreaInsets}from'react-native-safe-area-context';import*as Notifications from'expo-notifications';
import mobileAds from'react-native-google-mobile-ads';
import AdBanner from'./src/components/AdBanner';
import HomeScreen from'./src/screens/HomeScreen';import HistoryScreen from'./src/screens/HistoryScreen';import SettingsScreen from'./src/screens/SettingsScreen';import ScanScreen from'./src/screens/ScanScreen';import ManageCupsScreen from'./src/screens/ManageCupsScreen';import HistoryDayScreen from'./src/screens/HistoryDayScreen';import PremiumScreen from'./src/screens/PremiumScreen';import ThemesScreen from'./src/screens/ThemesScreen';import ThemeBuilderScreen from'./src/screens/ThemeBuilderScreen';import AnalyticsScreen from'./src/screens/AnalyticsScreen';import ChallengesScreen from'./src/screens/ChallengesScreen';import DataExportScreen from'./src/screens/DataExportScreen';import{ThemeProvider,useTheme}from'./src/context/ThemeContext';import{applyReminderSchedule,getReminderSettings,saveReminderSettings}from'./src/utils/notifications';import{subscribeToHydrateLinks}from'./src/utils/deepLinks';
if(typeof Notifications.setNotificationHandler==='function')Notifications.setNotificationHandler({handleNotification:async()=>({shouldShowBanner:true,shouldShowList:true,shouldShowAlert:true,shouldPlaySound:false,shouldSetBadge:false})});
const Tab=createBottomTabNavigator(),Stack=createNativeStackNavigator();const Icon=({emoji})=><Text style={{fontSize:20}}>{emoji}</Text>;
function Tabs(){const{colors:c}=useTheme();const insets=useSafeAreaInsets();const bottomPad=Math.max(6,insets.bottom);return <Tab.Navigator screenOptions={{tabBarActiveTintColor:c.primary,tabBarInactiveTintColor:c.textMuted,tabBarStyle:{backgroundColor:c.card,borderTopColor:c.border,height:50+bottomPad,paddingBottom:bottomPad,paddingTop:6},headerShown:false}}><Tab.Screen name="Home" component={HomeScreen} options={{tabBarIcon:()=> <Icon emoji="💧"/>}}/><Tab.Screen name="History" component={HistoryScreen} options={{tabBarIcon:()=> <Icon emoji="📅"/>}}/><Tab.Screen name="Settings" component={SettingsScreen} options={{tabBarIcon:()=> <Icon emoji="⚙️"/>}}/></Tab.Navigator>}
function Navigation(){const t=useTheme(),c=t.colors,dark=['midnight','halloween','newyear','champion'].includes(t.themeId),nav=useMemo(()=>({...dark?DarkTheme:DefaultTheme,colors:{primary:c.primary,background:c.background,card:c.card,text:c.text,border:c.border,notification:c.accent}}),[c,dark]);useEffect(()=>{const unsub=subscribeToHydrateLinks();getReminderSettings().then(async x=>{if(!x.enabled)return;const r=await applyReminderSchedule(x);if(r.status==='permission_denied'||r.status==='unsupported_web')await saveReminderSettings({...x,enabled:false})}).catch(()=>null);if(Platform.OS!=='web')mobileAds().initialize().catch(()=>null);return unsub},[]);return <NavigationContainer theme={nav}><StatusBar style={dark?'light':'dark'}/><View style={{flex:1}}><Stack.Navigator screenOptions={{headerStyle:{backgroundColor:c.card},headerTintColor:c.text,contentStyle:{backgroundColor:c.background}}}><Stack.Screen name="Tabs" component={Tabs} options={{headerShown:false}}/><Stack.Screen name="Scan" component={ScanScreen} options={{presentation:'modal',title:'Scan Bottle'}}/><Stack.Screen name="ManageCups" component={ManageCupsScreen} options={{presentation:'modal',title:'Manage Cups'}}/><Stack.Screen name="HistoryDay" component={HistoryDayScreen} options={({route})=>({title:route.params?.label?`Edit ${route.params.label}`:'Edit day'})}/><Stack.Screen name="Premium" component={PremiumScreen} options={{title:'Jug Up Plus'}}/><Stack.Screen name="Themes" component={ThemesScreen} options={{title:'Themes'}}/><Stack.Screen name="ThemeBuilder" component={ThemeBuilderScreen} options={{title:'Custom Theme'}}/><Stack.Screen name="Analytics" component={AnalyticsScreen} options={{title:'Analytics'}}/><Stack.Screen name="Challenges" component={ChallengesScreen} options={{title:'Challenges'}}/><Stack.Screen name="DataExport" component={DataExportScreen} options={{title:'Export & Backup'}}/></Stack.Navigator><AdBanner/></View></NavigationContainer>}
export default function App(){return <SafeAreaProvider><ThemeProvider><Navigation/></ThemeProvider></SafeAreaProvider>}
