import test from 'node:test';
import assert from 'node:assert/strict';
import { makeCustomTheme, resolveThemeId, seasonalThemeId, THEME_DEFINITIONS, themeHasAccess } from '../src/constants/themes.js';
const all=()=>true,none=()=>false;
test('holiday themes override broad seasons',()=>{assert.equal(seasonalThemeId(new Date('2026-10-31T12:00:00'),'',all),'halloween');assert.equal(seasonalThemeId(new Date('2026-12-20T12:00:00'),'',all),'christmas');assert.equal(seasonalThemeId(new Date('2026-12-30T12:00:00'),'',all),'newyear');assert.equal(seasonalThemeId(new Date('2026-07-14T12:00:00'),'',all),'summer')});
test('free users remain on standard automatic theme',()=>{assert.equal(resolveThemeId({selected:'auto',date:new Date('2026-10-31T12:00:00'),hasAccess:none}),'standard');assert.equal(themeHasAccess(THEME_DEFINITIONS.midnight,none),true);assert.equal(themeHasAccess(THEME_DEFINITIONS.summer,none),false)});
test('birthday and streak themes resolve for premium access',()=>{assert.equal(resolveThemeId({selected:'auto',date:new Date('2026-04-12T12:00:00'),birthday:'1990-04-12',hasAccess:all}),'birthday');assert.equal(resolveThemeId({selected:'auto',date:new Date('2026-04-13T12:00:00'),streak:30,hasAccess:all}),'champion')});
test('custom theme sanitises invalid colours',()=>{const t=makeCustomTheme({name:'Ocean',primary:'#112233',background:'bad'});assert.equal(t.name,'Ocean');assert.equal(t.colors.primary,'#112233');assert.equal(t.colors.background,THEME_DEFINITIONS.standard.colors.background)});
test('champion theme requires the actual streak, not just premium access',()=>{assert.equal(themeHasAccess(THEME_DEFINITIONS.champion,all,0),false);assert.equal(themeHasAccess(THEME_DEFINITIONS.champion,all,29),false);assert.equal(themeHasAccess(THEME_DEFINITIONS.champion,all,30),true);assert.notEqual(resolveThemeId({selected:'champion',date:new Date('2026-04-13T12:00:00'),streak:0,hasAccess:all}),'champion');assert.equal(resolveThemeId({selected:'champion',date:new Date('2026-04-13T12:00:00'),streak:30,hasAccess:all}),'champion')});
